@startuml
Title Cupcake Projekt

State index

State createuser


[*] --> index
index --> index : user or pw not OK
index --> createuser
createuser --> index : user created
createuser --> createuser : passwords doesn't match
index --> LoggedOnUser
index --> LoggedOnAdmin



state LoggedOnAdmin {
state admin
state user_admin
state cake
state users
State adminorderdetail

admin --> users: give money to user
admin --> cake: crude on cake
admin --> user_admin: se users and orders
user_admin --> adminorderdetail: se orderdetail and delete orders



}

state LoggedOnUser {

 state frontpage
 State orderdetail
 State orders
 state basket
 state checkout

 frontpage --> basket
 basket --> frontpage : edit basket
 frontpage --> orders
 orders --> frontpage
 orders --> orderdetail
 basket --> basket : not enough money
 basket --> checkout

}
  LoggedOnUser --> [*] : logout
  LoggedOnAdmin--> [*] : logout



@enduml