@startuml
Title Cupcake Projekt

State index
State adminorderdetail
State cake
State createuser


[*] --> index
index --> index : user or pw not OK
index --> createuser
createuser --> index : user created
createuser --> createuser : passwords doesn't match
index --> LoggedOnUser
index --> LoggedOnAdmin



state LoggedOnAdmin {
state user_admin
state order_admin
state orderedit_admin
    [*] --> user_admin
    user_admin --> order_admin
    order_admin --> orderedit_admin
    orderedit_admin --> order_admin : edit order


}

state LoggedOnUser {
 state users
 state frontpage
 State orderdetail
 State orders
 state basket
 state checkout
 [*] --> users
 users --> frontpage
 frontpage --> basket
 basket --> frontpage : edit basket
 frontpage --> orders
 orders --> frontpage
 orders --> orderdetail
 basket --> basket : not enough money
 basket --> checkout
 checkout --> [*]
}
@enduml