@startuml
Title Cupcake Projekt

State index

State createuser


[*] --> index
index --> index : user or pw not OK
index --> createuser
createuser --> index : user created
createuser --> createuser : passwords doesn't match
index --> LoggedOnUser
index --> LoggedOnAdmin



state LoggedOnAdmin {
state admin
state user_admin
state cake
state users
State adminorderdetail

admin --> users
admin --> cake
admin --> user_admin
user_admin --> adminorderdetail



}

state LoggedOnUser {

 state frontpage
 State orderdetail
 State orders
 state basket
 state checkout

 frontpage --> basket
 basket --> frontpage : edit basket
 frontpage --> orders
 orders --> frontpage
 orders --> orderdetail
 basket --> basket : not enough money
 basket --> checkout
 checkout --> [*]
}
@enduml